# Generated by Django 2.0 on 2018-03-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnlogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topoc',
            new_name='Topic',
        ),
    ]
