# Generated by Django 2.0 on 2018-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnlogs', '0007_entry_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='I18n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8)),
                ('untranslated_text', models.TextField(unique=True)),
                ('translated_text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='i18n',
            unique_together={('language', 'untranslated_text')},
        ),
    ]
