# Generated by Django 2.0 on 2018-04-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnlogs', '0008_auto_20180418_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i18n',
            name='untranslated_text',
            field=models.TextField(),
        ),
    ]
