# Generated by Django 2.0 on 2018-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnlogs', '0010_auto_20180418_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i18n',
            name='language',
            field=models.CharField(choices=[('zh-Hans', 'zh-Hans'), ('zh-Hant', 'zh-Hant'), ('en-US', 'en-US')], default='zh-Hans', max_length=8),
        ),
    ]
