# Generated by Django 2.0 on 2018-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnlogs', '0012_auto_20180420_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i18n',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('zh-hans', '简体中文'), ('zh-hant', '繁體中文')], default='zh-hans', max_length=8),
        ),
    ]
